from pyassimp import *
import datetime
import sys

print("modconv2 collision generator - mountainflaw")
if (len(sys.argv) > 3):
    print("Usage: python3 modconv.py PATHTOMODEL SCALE")
    exit()
fileName = str(sys.argv[1])
scale = int(sys.argv[2])

# Known formats will have labeled output depending on filename.
if fileName.endswith('.blend'):
    fileNameOut = fileName[:-5]
if fileName.endswith('.fbx') | fileName.endswith('.dae') | fileName.endswith('.obj'):
    fileNameOut = fileName[:-4]
else:
    fileNameOut = "output"
print(fileNameOut)
loopCount = 0
scene = load(fileName)
mesh = scene.meshes[0]
vertexCount = len(mesh.vertices)
vertexheader = open(fileNameOut + ".s", "w")
vertexheader.write("# Generated by modconv2\n")
vertexheader.write(".hword 0x0040, " + hex(vertexCount * 3) + "\n")
while (loopCount != vertexCount):
    print("Generating vertex " + str(loopCount))
    vertexheader.write(".hword " + str(int(mesh.vertices[loopCount][0]) * scale) + ", " + str(int(mesh.vertices[loopCount][1]) * scale) + ", " + str(int(mesh.vertices[loopCount][2]) * scale)
 + "\n")
    loopCount = loopCount + 1
print("Done.")
exit()
