#include <stdio.h>
#include <assimp/cimport.h>
#include <assimp/mesh.h>
#include <assimp/scene.h>

void model_convert_goddard(char *in, char *output, int scale) {
	char out[0x100];
	sprintf(out, "%sdynlist_.c", output);

	const struct aiScene *scene = aiImportFile(in, 0);
	struct aiMesh *mesh = scene->mMeshes[0];
	unsigned int vertexCount = mesh->mNumVertices;

	printf("Output: %s\n", output);
	printf("Verts:  %d\n", vertexCount);

	FILE *vertexSourcef = fopen(out, "w");
	fputs("// Dynlist generated by modconv4\n", vertexSourcef);

	puts("Generating Vertex Data...");

	fprintf(vertexSourcef, "#define VTX_NUM %d\n", vertexCount);
	fprintf(vertexSourcef, "s16 verts_%s[VTX_NUM][3] = {\n", output);

	for (size_t i = 0; i < vertexCount; i++) {
		int vertX = (int)mesh->mVertices[i].x * scale;
		int	vertY = (int)mesh->mVertices[i].y * scale;
		int	vertZ = (int)mesh->mVertices[i].z * scale;
		fprintf(vertexSourcef, "{%d,\t%d,\t%d},\n", vertX, vertY, vertZ);
	}

	fputs("};\n", vertexSourcef);
	fprintf(vertexSourcef, "GdVtxData vtx_%s_data = { VTX_NUM, 0x1, verts_%s };\n#undef VTX_NUM\n", output, output);

	puts("Vertex Generation: OK");
	puts("Generating Face Data...");

	fprintf(vertexSourcef, "#define FACE_NUM %d\n", vertexCount + 1);
	fprintf(vertexSourcef, "u16 facedata_%s[FACE_NUM][4] = {\n", output);

	for (unsigned int i = 0; i <= vertexCount; i += 3)
		fprintf(vertexSourcef, "{0,\t%d,\t%d,\t%d},\n", i, i + 1, i + 2);

	fputs("};\n", vertexSourcef);
	fprintf(vertexSourcef, "struct GdFaceData faces_%s_data = { FACE_NUM, 0x1, facedata_%s };\n#undef FACE_NUM\n", output, output);

	puts("FaceData Generation: OK");
	puts("Finished generating Goddard dynlist.");
	puts("Thank you.");
}

int main(int argc, char **argv) {
	puts("modconv - mountainflaw");

	if (argc != 4) {
		fprintf(stderr, "Usage: %s <model> <output> <scale>\n", argv[0]);
		return 1;
	}

	int scale;
	sscanf(argv[3], "%d", &scale);

	model_convert_goddard(argv[1], argv[2], scale);

	return 0;
}
